---
apiVersion: v1
kind: Service
metadata:
  name: external-url-checker
spec:
  selector:
    app: external-url-checker
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: {{ .Values.service.type }}
